### ISSUE TITLE
PCR Package. could not find function "pcr_analyze"

### ISSUE THREAD

**Issue by IgnaciaMeza** [MahShaaban/pcr#13]
Hey there,
I have been trying to use your R package for qPCR analysis. But R shows an error that the “pcr_analyze” function was not found.

So far I've done:

```r
# install package:
install.packages('pcr')

# load required libraries:
library(pcr)

# default mode delta_delta_ct
## locate and read raw ct data
fl <- system.file('extdata', 'ct1.csv', package = 'pcr')
ct1 <- read.csv(fl)

## add grouping variable
group_var <- rep(c('brain', 'kidney'), each = 6)
str(ct1)

# calculate all values and errors in one step 
res <- pcr_analyze(ct1,
                   group_var = group_var,
                   reference_gene = 'GAPDH',
                   reference_group = 'brain')
```

Here is when I get the error "Error in pcr_analyze(ct1, group_var = group_var, reference_gene = "GAPDH",  :   could not find function "pcr_analyze""

I am very new to R coding, so I might need a  more thorough explanation than experienced users!

Thanks!..

**Comment by MahShaaban** [comment]
Hi @IgnaciaMeza I edited the code in your comment so that it should run without errors. 
Please try it and report back if you got any errors.
