### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by danutasastre** [MahShaaban/pcr#14]
I'm a new R user and I'm having trouble installing your PCR package. I get the error below. Could you help me get this issue solved? Thanks!

> install.packages('pcr')
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/pcr_1.2.0.tgz'
Content type 'application/x-gzip' length 493549 bytes (481 KB)
==================================================
downloaded 481 KB

The downloaded binary packages are in
	/var/folders/m_/8j8153kd00v2nh0y1nw1vxww0000gn/T//RtmpZRNSHJ/downloaded_packages

> library(pcr)
Error: package or namespace load failed for ‘pcr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘rlang’

**Comment by MahShaaban** [comment]
Hi @danutasastre 
I think the problem is that you need to have a proper installation of `rlang` first. Why don't you try updating R and install `rlang` then try installing `pcr` again.
