### ISSUE TITLE
NA value

### ISSUE THREAD

**Issue by agrofak** [MahShaaban/pcr#15]
Hi
There are missing (NA) values in our datasets. How to use the function pcr_analyze? "na.rm = T" - does not work((
Andrei

**Comment by MahShaaban** [comment]
Hi @agrofak. You are right.
I think that it is better to deal with missing values before using `pcr_analyze`, either by removing or imputing them.
I added the `na.rm = TRUE` to the `mean` and `sd` calls in a new branch c838786465c0c24694825f6f3e6fc6f62ab96c07
You are install the modified branch and use it if you still think it's a good idea.
