### ISSUE TITLE
Aggregate in .pcr_average

### ISSUE THREAD

**Issue by Bisho2122** [MahShaaban/pcr#16]
Hello, 

The aggregate function used in .pcr_average, .pcr_sd and .pcr_cv sorts the groups in alphabetical order but not their corresponding values. So if the original order of groups in not sorted alphabetically, it will mess up the mean, sd and cv respectively, resulting in a reversed assignment of normalized values.

**Comment by MahShaaban** [comment]
Hi, @Bisho2122 
Would you please provide a minimal example to reproduce this behavior?

**Comment by Bisho2122** [comment]
I pulled up a request to update helper_function.R. I think the issue has been resolved
