### ISSUE TITLE
pcr

### ISSUE THREAD

**Issue by Paraudie** [MahShaaban/pcr#18]
Hi,
I have difficulty when I get to that level: "res<-pcr_analyze(ct1,group_var=group,reference_gene='RPS7',reference_group='Kisumu')
res <- pcr_analyze(ct1,group_var = group_var,reference_gene='RPS7',reference_group='Kisumu')";

here's what I get as a result; > res<-pcr_analyze(ct1,group_var=group,reference_gene='RPS7',reference_group='Kisumu')
Error in pcr_analyze(ct1, group_var = group, reference_gene = "RPS7",  : 
  could not find function "pcr_analyze"

Note: when I install the package and load "library 'pcr', this appears:
> library(pcr)
Erreur : package or namespace load failed for ‘pcr’:
 .onLoad a échoué dans loadNamespace() pour 'pillar', détails :
  appel : utils::packageVersion("vctrs")
  erreur : package ‘vctrs’ not found

Thanks for helping me

**Comment by MahShaaban** [comment]
Hi,

You probably need to install `vctrs` first. And try to load the `pcr` package, it should load without any error messages before you can use it.

**Comment by theneti3** [comment]
Hi,

I have the same problem:

fl <- system.file('extdata', 'ct1.csv', package = 'pcr')
ct1 <- read.csv(fl)

## add grouping variable
group_var <- rep(c('brain', 'kidney'), each = 6)
str(ct1)

# calculate all values and errors in one step 
res <- pcr_analyze(ct1,
                   group_var = group_var,
                   reference_gene = 'GAPDH',
                   reference_group = 'brain')

--> Fehler in pcr_analyze(ct1, group_var = group_var, reference_gene = "GAPDH",  : 
  konnte Funktion "pcr_analyze" nicht finden

Can anyone help?
thanks

**Comment by MahShaaban** [comment]
You need to make sure first that the package is installed properly and loaded before you can run this code.
