### ISSUE TITLE
Negative lower value while analysing the using standard curve

### ISSUE THREAD

**Issue by Navrique** [MahShaaban/pcr#20]
Dear @MahShaaban,
thank you a lot for developping this pcr package.
While using pcr analysis with the relative_curve method I got a strange output. The lower column of the output show me a negative value for one sample. I found it strange since the result should be express as expression relative to the control sample, in my case SC5314.
I was thinking it could be very useful to have access to all normalised and calibrated values, especially if you want to show result as box plot and dots. The second advantage would be to check incoherent results. Find below the matter to reproduce my error.
slopes = c(-3.065913, -2.868899)
intercept=c(17.31675, 18.71079)
Reference_groupe="SC5314"
Reference_gene="Cт.Mean.EFB1"
group_var=c(CEC3619, CEC3619, CEC3619, CEC5114, CEC5114, SC5314)
InputValue=
   Cт.Mean.EFB1 Cт.Mean.orf19_2713
5       19.9565            22.1486
6       19.9993            22.5788
7       19.6004            22.2507
8       20.0437            36.9872
9       19.4609            36.1748
11      20.2800            21.7199

here is the output tbl from pcr_analysis:
group               gene   normalized   calibrated        error      lower     upper
1  SC5314 Cт.Mean.orf19_2713 8.272646e-01 1.000000e+00           NA         NA        NA
2 CEC3619 Cт.Mean.orf19_2713 3.692645e-01 4.463681e-01 8.969421e-02  0.2034685 0.6892677
3 CEC5114 Cт.Mean.orf19_2713 3.782855e-06 4.572727e-06 2.041283e-06 -0.5396098 0.5396190

**Comment by MahShaaban** [comment]
Thanks @Navrique for reaching out.
If possible would you please provide a reproducible example. The example you provide doesn't run. You can use R package `reprex` for this purpose.
