### ISSUE TITLE
`group_var` don't support variable names with `_` (underscore)

### ISSUE THREAD

**Issue by lsilvam** [MahShaaban/pcr#24]
Hi @MahShaaban,

I found this situation (could it be a bug?) where the naming of the elements of the `group_var` for some reason leads to a wrong calculation of the `$calibrated` when one variable (in my case the `reference_group`) has an underscore, as you can see in the screenshot.
Oddly enough it substracts to it self, but then the subtractions to the other groups are not correct. 
In my case I named a group `total_dna`, and replacing it with `input`  instead fixed the error in the subtractions.

![rstudio_9afexzPffE](https://user-images.githubusercontent.com/53966548/113443287-92884800-93e9-11eb-96c8-33f12ceb0165.png)

**Comment by MahShaaban** [comment]
Hi @lsilvam 
Thanks for reaching out.
I reproduced your code below, and don't see the issue. Please make sure you are using the latest version of the package, it might be something that was fixed in a recent release.

``` r
# load the packages
library(pcr)
library(cowplot)

# recreate the example data
cq <- tibble::tibble(cq = c(30.4, 34.9, 31.7))

# define a group_var and run pcr_dct
groups1 <- c('input', 'IgG', 'PollII')
res2 <- pcr_dct(
  df = cq,
  group_var = groups1,
  reference_group = 'input',
  plot = TRUE
)

# rerun with group_var containing '_'
groups2 <- c('total_dna', 'IgG', 'PollII')
res1 <- pcr_dct(
  df = cq,
  group_var = groups2,
  reference_group = 'total_dna',
  plot = TRUE)

# extract and order the calibrated values
c1 <- res1$data$calibrated[which(res1$data$gene %in% groups1)]
c2 <- res2$data$calibrated[which(res2$data$gene %in% groups2)]

# are values equal?
all(c1 == c2)
#> [1] TRUE

# are plots equal?
plot_grid(res1, res2)
```

![](https://i.imgur.com/yDqeFlk.png)

<sup>Created on 2021-04-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by lsilvam** [comment]
@MahShaaban yes, that might be the case; I was using the commit c838786465c0c24694825f6f3e6fc6f62ab96c07
Good to know that it is no longer an issue in recent versions.
Thank you
