### ISSUE TITLE
CpAverage or CrossingPoint 

### ISSUE THREAD

**Issue by lmanchon** [MahShaaban/pcr#25]
--Hi all,

I have a question about the output ixo files from the Lightcycler 480: 
in these files there are the CpAverage and CrossingPoint values.
What values do I need to retrieve to use the pcr package?

Thanks

**Comment by MahShaaban** [comment]
Hi @lmanchon 
I am not familiar with this particular machine. However, I think, it's the cp Average you should use. If you could provide an example file from the machine output, I might be able to confirm.
Cheers

**Comment by lmanchon** [comment]
--Hi,
 
ok you can find an example in attachment here.
thanks.
[TNFa.ixo.gz](https://github.com/MahShaaban/pcr/files/6832248/TNFa.ixo.gz)

**Comment by MahShaaban** [comment]
I can't open .ixo files on my machine. Is there a way to export the data into .txt files? If no, you could copy the relevant parts into a text file and share it.

**Comment by lmanchon** [comment]
-- 
ixo file is just a text file.
You can open it with notepad+ on Windows machine or just with vim or vi on Linux system.

**Comment by MahShaaban** [comment]
Yes. I can. I am not sure however which of lines are relevant to the question.

**Comment by lmanchon** [comment]
--
you can use grep to catch the lines with "CpAverage" or "CrossingPoint".
eaF1 is the gene control.
