### ISSUE TITLE
pcr_wilcox function

### ISSUE THREAD

**Issue by lmanchon** [MahShaaban/pcr#27]
--Hi,

I get different pvalues when I use directly the wilcox.test function on my series of values.
Why does the pcr_wilcox function of the package return a different pvalue?

thank you --

**Comment by MahShaaban** [comment]
Would you please provide an example of the different values?

**Comment by lmanchon** [comment]
ok, sorry,  i found my problem, you use a '.pcr_normalize' function in your package to normalize the values , i missed that.
But why to normalize the data when using a Wilcoxon test ?
The data must be normally distributed for a T-test and not for a Wilcoxon test, right ?

**Comment by MahShaaban** [comment]
`.pcr_normalize` normalize the gene of interest to the reference gene. This, I think, is quite different from the input values to the test functions being normally distributed or not.

**Comment by lmanchon** [comment]
ok.
not sure it makes much difference to normalize the values in the Wilcoxon test cases.
