### ISSUE TITLE
Add p-values on the plot

### ISSUE THREAD

**Issue by Ariadneyuan** [MahShaaban/pcr#28]
Hi! 
Thank you for developing this wonderful package.

I got confused at adding p values calculated by 'pcr_test' to ggplot when there were several genes included in a single run.
Here's the plot I got using 'pcr_analyze' and 'ggplot'
![image](https://user-images.githubusercontent.com/88684224/128765443-6bdd1c3d-da90-4657-bb1b-d1b1e9934fe5.png)

And here are the p values I got using 'pcr_test'.
` gene    estimate      p_value      lower      upper
1 gene2 -0.44260692 6.629252e-02 -0.9348677 0.04965387
2 gene3  0.02309579 8.166044e-01 -0.2375637 0.28375527
3 gene4  2.86152226 1.150798e-02  1.4078153 4.31522920
4 gene5  1.21538222 1.974057e-05  1.0795814 1.35118304
5 gene6  0.98096805 1.806444e-01 -0.7195197 2.68145577`  

Is there a way to add p values to the plot? 

Many thanks in advance for your help!

Ariadne

**Comment by MahShaaban** [comment]
Hi @Ariadneyuan 
Thanks for reaching out. There is no way in `pcr` to add p-values or any annotation to the plot for that matter. I would suggest something like the following.
``` r
# load libraries
library(pcr)
library(tidyverse)

# applying the delta delta ct method
## locate and read raw ct data
fl <- system.file('extdata', 'ct1.csv', package = 'pcr')
ct1 <- read.csv(fl)

# add grouping variable
group_var <- rep(c('brain', 'kidney'), each = 6)

# calculate all values and errors in one step
res <- pcr_analyze(ct1,
                   group_var = group_var,
                   reference_gene = 'GAPDH',
                   reference_group = 'brain')
res
#>    group  gene normalized calibrated relative_expression      error    lower
#> 1  brain c_myc      6.860      0.000            1.000000 0.17395402 0.886410
#> 2 kidney c_myc      4.365     -2.495            5.637283 0.09544632 5.276399
#>      upper
#> 1 1.128146
#> 2 6.022850
# apply test
tst <- pcr_test(ct1,
                group_var = group_var,
                reference_gene = 'GAPDH',
                reference_group = 'brain')

tst
#>    gene estimate      p_value     lower     upper
#> 1 c_myc   -2.495 3.466603e-10 -2.680535 -2.309465
tst$p_value < 0.001
#> [1] TRUE

# make a plot
pp <- res %>%
  ggplot(aes(x = gene, y = relative_expression,
             ymin = lower, ymax = upper,
             fill = group)) +
  geom_col(position = position_dodge()) +
  geom_errorbar(position = position_dodge())
pp
```

![](https://i.imgur.com/MQsIWpt.png)

``` r
# annotate plot with a pvalue
pp +
  annotate('text',
           x = unique(tst$gene),
           y = 6.5,
           label = 'P < 0.001')
```

![](https://i.imgur.com/A5ec5Ze.png)

<sup>Created on 2021-08-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by Ariadneyuan** [comment]
Hi @MahShaaban

Thanks for your reply!
I'll try to add p values manually following your directions. 

Ariadne
