### ISSUE TITLE
Importing from QuantStudio file?

### ISSUE THREAD

**Issue by SimoniMD** [MahShaaban/pcr#29]
Hi! Thanks for this package.

It looks like I need to import a .csv, but cannot figure out from the vignette how the .csv is supposed to be structured. I have a .xls and .eds from QuantStudio. Is there a wrapper I should use first? Or an example you may have of how it is supposed to look? Thanks for any assistance

-Michael

**Comment by MahShaaban** [comment]
Hi @SimoniMD 
Your csv file could look something like this, [ct1.csv](https://github.com/MahShaaban/pcr/blob/a6402a1436582a0ef78ed463ced274a64b06f340/inst/extdata/ct1.csv)
You can use your preferred method to load the CT values in R. The input data should be a `data.frame` with genes in the columns and samples in the rows. So if you have an experiment with two primers in two conditions three replicates each, there should be CT values in a 6 x 2 `data.frame`.
For your reference, each section in the vignette describes the input data for each function, usually in the first paragraph. For example, see the "Double delta C_t" section.
