### ISSUE TITLE
Does calculated error represents Standard deviation? 

### ISSUE THREAD

**Issue by shubham7193** [MahShaaban/pcr#30]
Hi,
I just wanted to know how the error is being calculated for relative expression values and is this error value represents standard deviation?
Please do let me know.
Regards,
Shubham

**Comment by MahShaaban** [comment]
Hi @shubham7193 
Thanks for reaching out. As explained in the package vignette the error term in the <img src="https://render.githubusercontent.com/render/math?math=\Delta\Delta C_T"> model is given by the square root of the sum of the squared standard deviation of the gene of interest and the reference or 
(<img src="https://render.githubusercontent.com/render/math?math=\sqrt{s_1^2 %2B s_2^2}">).

**Comment by shubham7193** [comment]
Hi,
Thanks for your reply. I am still confused because if this formula is being used for error then the value of the error would be the same for both control and treated samples?
Also, after plotting the pcr_analyze, it plots upper and lower values on the error bars, how can we plot SD values on the graph?
Please do let me know if my question is not very clear.

**Comment by MahShaaban** [comment]
- No. The control condition is not calibrated by anything (or by itself sot to speak), so the error term is the standard decision. For the other conditions, the error is propagated, that is taking into account the error in the control condition, hence that formula.
- To use the plotting option you have to use the error term as calculated. In the vignette, I reference a paper on this model where the recommendation was to do error propagation whose interpretation doesn't differ much from the standard deviation.
