### ISSUE TITLE
rOpenSci review for qPCR package

### ISSUE THREAD

**Issue by wolski** [MahShaaban/pcr#32]
Hello,

You might be interested to know that there is a review ongoing for a qPCR package on rOpenSci
https://github.com/ropensci/software-review/issues/470

Could help me to determine if the package under review fulfills the best in category criteria?

https://devguide.ropensci.org/policies.html#overlap

Thank you

**Comment by MahShaaban** [comment]
Thanks, @wolski for reaching out.
Let me say first that I don't understand the best in category criteria. A "best" in category judgment would require formal testing of the relevant packages, several of which are good at what they set out to do.

That said, I agree with much of the reviews in the issue
- The submitted package offers features absent from existing packages
- The comparison with exiting packages is lacking or inaccurate
- (More of a question) To my knowledge, rOpenSci doesn't consider stats packages. This submission is a "field and lab reproducibility tools," so shouldn't it be evaluated/compared to others in the category and not just as a PCR package?

**Comment by ewallace** [comment]
@MahShaaban thanks for the generous comments. If you do have any other feedback on [tidyqpcr](https://github.com/ewallace/tidyqpcr/), we would love to hear it.

For what it's worth - tidyqpcr started life as my own scripts in 2016, and turned into a package in 2019. Ours started as a "qPCR analysis for tidyverse users who like all the data to be exposed and also run the experiments themselves." So it emphasises every object being a data frame, and also emphasises plate design which is practically useful for experimental setup.

We found out about your package, qpcr, in early 2020 while doing the eLife open innovation leaders course. 

I appreciate the way that your package, pcr, has nice functions for standard analyses, as well as being nicely presented with tests and best practices.

So I agree with your point that different packages set out to do different things and are good at what they set out to do.

**Comment by MahShaaban** [comment]
Thanks @ewallace 
I love how your package deals with the practical aspects of the experiments and doesn't ask too much of the user. The well-documented code and the vignettes are very helpful.
I hope to see `tidyqpcr` in the rOpenSci suite soon

**Comment by ewallace** [comment]
Hello @MahShaaban. We just updated our [tidyqpcr](/ewallace/tidyqpcr) package in response to the rOpenSci review comments.

If you did have any more comments and feedback on the package, we would love to see them.
