### ISSUE TITLE
Handling different starting sample masses

### ISSUE THREAD

**Issue by JacobRPrice** [MahShaaban/pcr#34]
Is there a way to integrate sample mass (prior to DNA extraction) into our analysis, or scaling the results to account for different starting sample masses using the `pcr` package?

**Comment by MahShaaban** [comment]
The only way I can think of is to use `pcr_test` with the option `test = 'lm'`. You can include any arbitrary variable in a linear model and estimate/control for its effect.

**Comment by JacobRPrice** [comment]
Hi @MahShaaban , thank you for the suggestion, I can give that a try. 

At this point do you have any plans on developing or expanding the `pcr` package to include absolute abundance calculations and associated statistical tests? If so, the inclusion of sample mass information would be best implemented at that time.

**Comment by MahShaaban** [comment]
I am certainly open to the idea. If you like, you can kick start this feature by opening a new issue and providing some help on how it can be implemented.
