### ISSUE TITLE
Corrupt file - pcr.rdb

### ISSUE THREAD

**Issue by ncrawford0809** [MahShaaban/pcr#8]
I am attempting to run an analysis utilizing either pcr_analyze or pcr_ddct and I receive warnings shown below:
Error: lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/pcr/R/**pcr.rdb' is corrupt**
In addition: Warning messages:
1: In args(pcr_ddct) : restarting interrupted promise evaluation
2: In args(pcr_ddct) : internal error -3 in R_decompress1

What can be done to fix the issue to continue my analysis

**Comment by MahShaaban** [comment]
I would suggest you restart your R session then load only the packages you need for the analysis.
If the problem didn't go away, please update to the the latest R version and reinstall `pcr`.
If neither works, please give some details about your machine setup and R environment.
